# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Mavor < Formula
  desc "Local, low-latency voice dictation — hotkey to talk, text lands where you type"
  homepage "https://github.com/mschulkind-oss/mavor"
  version "0.1.1"
  license "Apache-2.0"

  depends_on "whisper-cpp"
  depends_on "wl-clipboard"
  depends_on "wtype"
  depends_on :linux

  if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
    url "https://github.com/mschulkind-oss/mavor/releases/download/v0.1.1/mavor_0.1.1_linux_amd64.tar.gz"
    sha256 "267497fe2ed5324457e72e5e5046f9b4e4caed0e65dd043af489d35d9f93385f"
    define_method(:install) do
      bin.install "mavor"
      lib.install "libonnxruntime.so", "libsherpa-onnx-c-api.so"
    end
  end

  def caveats
    <<~EOS
      mavor needs a Wayland compositor implementing wlr-layer-shell and
      virtual-keyboard-v1: sway, Hyprland, river, Wayfire, niri, labwc. It
      does not work under GNOME, which implements neither.

      Get started with:
        mavor setup     # scaffold config, install tools, fetch a model
        mavor doctor    # check the environment
    EOS
  end

  test do
    system "#{bin}/mavor", "version"
  end
end
