# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Swarf < Formula
  desc "Invisible, auto-syncing personal storage for any git repo"
  homepage "https://github.com/mschulkind-oss/swarf"
  version "0.4.0"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mschulkind-oss/swarf/releases/download/v0.4.0/swarf_0.4.0_darwin_amd64.tar.gz"
      sha256 "3c721e1fecab49d2daaf52e8a82d0f7c76c0d199840ecf7d4fb7ec84b5f3115f"

      define_method(:install) do
        bin.install "swarf"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mschulkind-oss/swarf/releases/download/v0.4.0/swarf_0.4.0_darwin_arm64.tar.gz"
      sha256 "dd14fead02d483b5d3544b2c628b66c1d49850265e0802c31dd53171ee37d885"

      define_method(:install) do
        bin.install "swarf"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mschulkind-oss/swarf/releases/download/v0.4.0/swarf_0.4.0_linux_amd64.tar.gz"
      sha256 "4828d05fd18a5c9397aabd821ca48171181940ab4fefd0fc694f480f5704e638"
      define_method(:install) do
        bin.install "swarf"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mschulkind-oss/swarf/releases/download/v0.4.0/swarf_0.4.0_linux_arm64.tar.gz"
      sha256 "0ed064222c63451bb98218bc653f887fdf7c8b89771b9dac80f01912a81ac3cb"
      define_method(:install) do
        bin.install "swarf"
      end
    end
  end

  test do
    system "#{bin}/swarf", "--version"
  end
end
