# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Waxon < Formula
  desc "A slide deck toolkit built for the mind meld between human and agent"
  homepage "https://github.com/mschulkind-oss/waxon"
  version "0.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/mschulkind-oss/waxon/releases/download/v0.1.1/waxon-0.1.1-darwin-amd64.tar.gz"
      sha256 "53ec37684f0abab694a1876ee58a2bc013ae09289233fdeb2581952fbfd81d84"

      define_method(:install) do
        bin.install "waxon"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/mschulkind-oss/waxon/releases/download/v0.1.1/waxon-0.1.1-darwin-arm64.tar.gz"
      sha256 "3ab8ceb066e3fe9c37cebbe352ef35380f826f571cab49c1c6f7594b0ee22b0e"

      define_method(:install) do
        bin.install "waxon"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/mschulkind-oss/waxon/releases/download/v0.1.1/waxon-0.1.1-linux-amd64.tar.gz"
      sha256 "16ac7979b49781e8552bef7fb74a5e724fa2886ebffc8e98f5d91c7bb14f687b"
      define_method(:install) do
        bin.install "waxon"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/mschulkind-oss/waxon/releases/download/v0.1.1/waxon-0.1.1-linux-arm64.tar.gz"
      sha256 "326ec8e8bbdbfd5ad22d0d8d8c6b3efcc2f6f735b059e80964caacc6f4236517"
      define_method(:install) do
        bin.install "waxon"
      end
    end
  end

  test do
    system "#{bin}/waxon", "--version"
  end
end
